"""agregar logo plan foto usuario

Revision ID: 2cc98dd65d90
Revises: f1650350bba0
Create Date: 2026-03-17 23:06:21.203356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cc98dd65d90'
down_revision: Union[str, Sequence[str], None] = 'f1650350bba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('barberia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['barberia_id'], ['barberias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.add_column('barberias', sa.Column('logo', sa.String(), nullable=True))
    op.add_column('barberias', sa.Column('plan', sa.String(), nullable=True))
    op.add_column('barberos', sa.Column('foto', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('barberos', 'foto')
    op.drop_column('barberias', 'plan')
    op.drop_column('barberias', 'logo')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
